site_name: Krellian Documentation
site_url: https://docs.krellian.com
site_description: 'Documentation for Krellian products and services'
copyright: '© Krellian Ltd.'
nav:
    - 'Krellian Cloud':
      - 'Sign Up': 'cloud/sign-up.md'
      - 'Log In': 'cloud/log-in.md'
      - 'Devices': 'cloud/devices.md'
      - 'Buildings': 'cloud/buildings.md'
      - 'Analytics': 'cloud/analytics.md'
      - 'Profile': 'cloud/profile.md'
      - 'Log Out': 'cloud/log-out.md'
theme: 
    name: readthedocs
    logo: 'images/logo.svg'
